/**
 * Provenance badge and caveat list.
 *
 * These two components exist because the project serves a model trained on
 * labels it generated itself. A number without its provenance is the failure
 * mode the whole repository is written against, so every component that renders
 * a prediction renders these beside it - the badge is not decoration.
 */

import type { Labels } from "../types";

export function ProvenanceBadge({ labels }: { labels: Labels }) {
  const synthetic = labels === "SYNTHETIC";
  return (
    <span
      className={`badge ${synthetic ? "badge-synthetic" : "badge-observed"}`}
      title={
        synthetic
          ? "Labels generated by this project from ecological response curves - not measured in the field"
          : "Labels are real measurements from the public-waters monitoring record"
      }
    >
      {synthetic ? "⚠ Synthetic labels" : "Observed labels"}
    </span>
  );
}

export function CaveatList({
  caveats,
  labels,
}: {
  caveats: string[];
  labels?: Labels;
}) {
  if (caveats.length === 0) return null;
  return (
    <div className={`caveats ${labels === "SYNTHETIC" ? "synthetic" : ""}`}>
      <h3>Read with the number</h3>
      <ul>
        {caveats.map((caveat) => (
          <li key={caveat}>{caveat}</li>
        ))}
      </ul>
    </div>
  );
}

export function ErrorBanner({ message }: { message: string }) {
  return (
    <div className="banner banner-error" role="alert">
      {message}
    </div>
  );
}
