"""FastAPI application.

Serves two models side by side: dissolved oxygen, trained on real measurements,
and the synthetic habitat index. Both are exposed with their provenance and
caveats attached, because a caller who sees only a number cannot tell which is
which - and one of them is a function this repository wrote.

Run with::

    uvicorn aquanexus.api.app:app --reload
"""

from __future__ import annotations

import time
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from aquanexus.api.registry import registry
from aquanexus.api.routes import explanations, health, predictions, scenarios
from aquanexus.config import settings
from aquanexus.logger import get_logger

log = get_logger("api.app")

DESCRIPTION = """
Physics-informed habitat and water quality prediction for the Ayase River (綾瀬川),
Saitama, Japan.

**Two models are served, and they are not equivalent.**

* `dissolved_oxygen` — trained on **real measurements** from the public-waters
  monitoring record. R² ≈ 0.44 under cross-validation with whole stations held
  out, which is only marginally better than assuming no change since the previous
  sample. Unreliable at low flow.
* `hsi` — habitat suitability index, trained on **synthetic labels generated by
  this project**. Its high accuracy measures recovery of a known function, not
  ecological skill.

Every prediction response carries the relevant caveats. Call `GET /models` first.
"""


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load models once at startup.

    A failure to load is logged and surfaced through /health rather than
    preventing start: an API that can explain why it is degraded is more useful
    than one that will not boot.
    """
    registry.load()
    if registry.ready:
        log.info("ready with model(s): %s", sorted(registry.models))
    else:
        log.error("started with no models: %s", registry.error)
    yield
    registry.models.clear()


app = FastAPI(
    title=settings.PROJECT_NAME,
    version=settings.VERSION,
    description=DESCRIPTION,
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def timing_and_errors(request: Request, call_next):
    """Time every request and convert unhandled errors into JSON.

    Without this an unexpected exception returns an HTML traceback page, which
    is both unhelpful to an API client and a small information leak.
    """
    started = time.perf_counter()
    try:
        response = await call_next(request)
    except Exception:  # noqa: BLE001 - deliberate catch-all at the boundary
        elapsed = (time.perf_counter() - started) * 1000
        log.exception("unhandled error on %s %s after %.0f ms",
                      request.method, request.url.path, elapsed)
        return JSONResponse(
            status_code=500,
            content={"detail": "internal error", "path": request.url.path},
        )

    elapsed = (time.perf_counter() - started) * 1000
    response.headers["X-Response-Time-ms"] = f"{elapsed:.1f}"
    log.debug("%s %s -> %d in %.1f ms", request.method, request.url.path,
              response.status_code, elapsed)
    return response


app.include_router(health.router)
app.include_router(predictions.router)
app.include_router(scenarios.router)
app.include_router(explanations.router)


@app.get("/", tags=["meta"], summary="Service description")
def root() -> dict:
    return {
        "name": settings.PROJECT_NAME,
        "version": settings.VERSION,
        "river": f"{settings.RIVER_NAME} ({settings.RIVER_NAME_JA})",
        "docs": "/docs",
        "models": sorted(registry.models),
        "note": "Two models are served with different label provenance. "
                "See GET /models before use.",
    }
