/**
 * About: sources, method, and the standing list of what does not work.
 *
 * The limitations are on the same page as the description, not behind a
 * disclosure. They are the most useful thing here for anyone deciding whether
 * to trust an output.
 */

export default function About() {
  return (
    <>
      <h1>About</h1>

      <section className="card prose">
        <h2>What this is</h2>
        <p>
          A proof of concept that goes from Japanese open environmental data to a
          served, explainable model: bathymetric point clouds → HEC-RAS
          hydraulics → a joined dataset → two trained models → this interface.
        </p>
        <p>
          The study reach is 27.5 km of the Ayase River (綾瀬川) in Saitama,
          described by 49 cross-sections — four of the 53 extracted were cut
          through bank where the centreline wandered, and are excluded.
        </p>
      </section>

      <section className="card prose">
        <h2>Where the data comes from</h2>
        <ul>
          <li>
            <strong>Channel bathymetry</strong> — 埼玉県 河川点群データ (CC BY
            4.0). UAV survey plus narrow multibeam echosounder, so it includes the
            submerged bed that topographic LiDAR cannot see.
          </li>
          <li>
            <strong>Water quality</strong> — 環境省 水環境総合情報サイト and 埼玉県
            公共用水域水質測定. Monthly grab samples with co-measured discharge and
            temperature.
          </li>
          <li>
            <strong>Meteorology</strong> — 気象庁 過去の気象データ.
          </li>
          <li>
            <strong>Biology</strong> — 河川水辺の国勢調査, used for independent
            checking rather than training: only six survey records cover this
            reach.
          </li>
        </ul>
      </section>

      <section className="card prose">
        <h2>The two models</h2>
        <p>
          <strong>Dissolved oxygen</strong> is trained on 138 real measurements
          from four stations, cross-validated with whole stations held out. R²
          0.39, RMSE 1.79 mg/L. Ridge regression beats both tree models at this
          sample size, which is the opposite of what the project plan assumed.
        </p>
        <p>
          <strong>Habitat suitability</strong> is trained on labels generated by
          this project from ecological response curves. Its R² of 0.99 measures
          recovery of a function the repository itself wrote. It is served
          because scenario work needs a bounded habitat score, and it is marked
          synthetic everywhere it appears.
        </p>
      </section>

      <section className="card prose">
        <h2>What does not work</h2>
        <ul>
          <li>
            <strong>Low flow.</strong> Below about 2 m³/s the oxygen model is
            biased roughly −2 mg/L, and most of its low-flow evidence comes from
            one shallow upstream station. Drought is when oxygen matters most and
            where this model is weakest.
          </li>
          <li>
            <strong>Scenarios are not simulations.</strong> Changing discharge
            re-interpolates depth, velocity and width from the HEC-RAS sweep, so
            the state is coherent — but the sweep is precomputed, and the answer
            is a sensitivity of the fitted relationship, not a forecast.
          </li>
          <li>
            <strong>The model cannot reach the extremes.</strong> Observed oxygen
            spans 3.0–17.0 mg/L; out-of-fold predictions span 4.2–10.2. It cannot
            flag a hypoxic event.
          </li>
          <li>
            <strong>It transfers only inside its evidence.</strong> Applied
            unchanged to a river it has never seen — the Naka, held out from the
            start — it scores R² +0.34 where inputs are in range and −0.90
            outside, pooling to −0.08: worse than that river&rsquo;s own mean. The
            out-of-range flag on every prediction is the line between those two.
          </li>
          <li>
            <strong>Ten collinear feature pairs.</strong> The hydraulic features
            are all derived from discharge, so individual SHAP contributions
            cannot be ranked against each other.
          </li>
          <li>
            <strong>A retracted finding.</strong> An earlier run reported
            temperature × discharge interacting synergistically at −1.02 mg/L.
            That came from one station's 48 observations; pooled over all 138 the
            sign reverses. It is not established.
          </li>
          <li>
            <strong>Uncalibrated roughness.</strong> No gauged rating curve
            exists for this reach, so Manning's n was set from a textbook. Across
            its plausible range the predictions move by up to 0.26 mg/L — 15% of
            the model's error — which makes one rating curve the most valuable
            measurement still missing, though a smaller problem than the geometry
            already corrected.
          </li>
        </ul>
      </section>

      <section className="card prose">
        <h2>Source</h2>
        <p>
          Code, notebooks and the development log:{" "}
          <a
            href="https://github.com/kiruthick01/AquaNexus"
            target="_blank"
            rel="noreferrer"
          >
            github.com/kiruthick01/AquaNexus
          </a>
          . The API documents itself at <code>/docs</code>.
        </p>
      </section>
    </>
  );
}
