/**
 * Home: what is being served, and what it is worth.
 *
 * The dashboard the plan asked for. It leads with the difference between the
 * two models rather than with a number, because that difference is the thing a
 * first-time visitor most needs and is least likely to ask about.
 */

import { Link } from "react-router-dom";

import { ProvenanceBadge } from "../components/Provenance";
import type { ModelInfo } from "../types";
import type { ModelState } from "../useModels";

export default function Home({ models }: { models: ModelState }) {
  const river = models.health?.river ?? "Ayase (綾瀬川)";

  return (
    <>
      <h1>Two models answer here. Only one of them is measuring the river.</h1>
      <p className="prose">
        {river} runs through Saitama, and spent years ranked as Japan’s most
        polluted river before a documented recovery. This reads its channel
        geometry from open bathymetric point clouds, its hydraulics from HEC-RAS,
        and predicts from what came out — with the standing of every number
        attached to it.
      </p>

      <div className="split">
        {models.models.map((model) => (
          <ModelSummary key={model.target} model={model} />
        ))}
      </div>

      <section className="card">
        <div className="card-title">
          <h2>Where to start</h2>
        </div>
        <ul className="prose">
          <li>
            <Link to="/predict">Predict</Link> — one environmental state, one
            number, with its explanation.
          </li>
          <li>
            <Link to="/scenarios">Scenarios</Link> — change discharge or
            temperature and see how the model responds.
          </li>
          <li>
            <Link to="/analyze">Analyze</Link> — sweep a grid of conditions and
            look at the shape of what was learned.
          </li>
          <li>
            <Link to="/about">About</Link> — the data, the method, and the parts
            that do not work.
          </li>
        </ul>
      </section>
    </>
  );
}

function ModelSummary({ model }: { model: ModelInfo }) {
  const r2 = typeof model.metrics.r2 === "number" ? model.metrics.r2 : null;
  const rmse = typeof model.metrics.rmse === "number" ? model.metrics.rmse : null;
  const synthetic = model.labels === "SYNTHETIC";

  return (
    <section className={`card model-sheet ${synthetic ? "synthetic" : ""}`}>
      <div className="card-title">
        <h2>{model.target === "hsi" ? "Habitat index" : "Dissolved oxygen"}</h2>
        <ProvenanceBadge labels={model.labels} />
      </div>

      <p className="small">
        {synthetic
          ? "Labels are generated by this project from ecological response curves. A high score here measures how well a regressor recovers a known function — not ecological skill. It is served because scenario analysis needs a bounded habitat score."
          : "Labels are real measurements from the public-waters monitoring record. This is the model worth believing, and it is a modest result: it beats “same as last month” by 0.06 R² and loses to it on median error."}
      </p>

      <div className="facts">
        {r2 !== null && (
          <div>
            <div className="stat-label">R²</div>
            <div className="stat-value">{r2.toFixed(3)}</div>
          </div>
        )}
        {rmse !== null && (
          <div>
            <div className="stat-label">RMSE</div>
            <div className="stat-value">
              {rmse.toFixed(3)} {model.unit}
            </div>
          </div>
        )}
        <div>
          <div className="stat-label">Rows</div>
          <div className="stat-value">{model.n_train.toLocaleString()}</div>
        </div>
        <div>
          <div className="stat-label">Model</div>
          <div className="stat-value">{model.model_type}</div>
        </div>
      </div>
    </section>
  );
}
