"""Do the four bad cross-sections change the answer?

The validator flags four sections whose channel is far narrower than their
neighbours - RS 12500, 14000, 18000 and 24000, at 11-37 m against neighbours of
34-155 m. They are not constrictions in the river; they are places where the
centreline, derived from tile centroids, wanders off the channel and the cut
catches a slice of bank.

They have been flagged and kept since Phase 1c, on the grounds that dropping
them was a judgement call nobody had measured. This measures it: re-run the
sweep with the sections excluded, and compare the predictions.

The decision it informs is not "are these sections wrong" - they are - but "does
removing them change any conclusion enough to be worth retraining and restating
every number in the project".

    python scripts/constriction_impact.py

Needs HEC-RAS on Windows. Writes docs/CONSTRICTION_IMPACT.md.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from aquanexus.config import settings
from aquanexus.data.validator import validate_sections
from aquanexus.hecras.reader import read_geometry
from aquanexus.logger import get_logger

sys.path.insert(0, str(Path(__file__).resolve().parent))
from manning_sensitivity import (  # noqa: E402
    BASELINE,
    RMSE,
    prediction_shift,
    reach_means,
    run_one,
)

log = get_logger("scripts.constriction_impact")

SOURCE_PROJECT = settings.HECRAS_DIR / "ayase_sweep"

#: Worst-case prediction shift from the roughness study, for comparison.
MANNING_WORST = 1.098

ALL = "all 53"
TRIMMED = "constrictions dropped"


def flagged_stations(sections) -> list[float]:
    """River stations the validator calls constrictions.

    Read from the validator rather than hard-coded: if the geometry is rebuilt
    with a better centreline, this study should follow the new verdict instead
    of the old station numbers.
    """
    report = validate_sections(sections)

    # The Issue carries `check` and `location` as fields. An earlier version of
    # this function matched on the rendered message instead, and "0" matched
    # inside "12500" - so it dropped RS 0, a 157 m section, and reported the
    # answer to a question nobody asked.
    stations = []
    for issue in report.warnings:
        if issue.check != "section.constriction":
            continue
        station = issue.location.removeprefix("RS ").strip()
        try:
            stations.append(float(station))
        except ValueError:
            log.warning("could not read a station from %r", issue.location)
    return sorted(set(stations))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-run", action="store_true")
    parser.add_argument("--keep", action="store_true")
    args = parser.parse_args()

    geometry = SOURCE_PROJECT / "Ayase.g01"
    if not geometry.is_file():
        log.error("no geometry at %s", geometry)
        return 1

    sections = sorted(read_geometry(geometry)[0].sections,
                      key=lambda s: s.river_station)
    dropped = flagged_stations(sections)
    if not dropped:
        log.error("the validator flags no constrictions; nothing to compare")
        return 1

    kept = [s for s in sections if s.river_station not in dropped]
    log.info("%d section(s); dropping %d: %s",
             len(sections), len(dropped), ", ".join(f"RS {d:.0f}" for d in dropped))

    work_root = settings.HECRAS_DIR / "constrictions"
    frames = []
    for label, subset in ((ALL, sections), (TRIMMED, kept)):
        out_dir = work_root / ("all" if label == ALL else "trimmed")
        frame = run_one(subset, BASELINE, out_dir, compute=not args.no_run)
        frame["variant"] = label
        frames.append(frame)

    results = pd.concat(frames, ignore_index=True)
    means = reach_means(results, key="variant")
    shifts = prediction_shift(means, key="variant", baseline=ALL)

    document = write_report(sections, dropped, means, shifts)
    Path("docs/CONSTRICTION_IMPACT.md").write_text(document, encoding="utf-8")
    log.info("wrote docs/CONSTRICTION_IMPACT.md")
    print(document)

    if not args.keep and not args.no_run:
        shutil.rmtree(work_root, ignore_errors=True)
    return 0


def write_report(sections, dropped, means, shifts) -> str:
    widths = {s.river_station: s.width for s in sections}
    ordered = sorted(widths)

    lines = [
        "# The four flagged cross-sections",
        "",
        "Generated by `scripts/constriction_impact.py`.",
        "",
        "The validator flags four sections as constrictions: the channel is far "
        "narrower than at either neighbour, because the centreline wanders off "
        "the channel and the cut catches a slice of bank. They are artefacts of "
        "the extraction, not features of the river.",
        "",
        "| section | width | neighbours |",
        "|---|---|---|",
    ]
    for station in dropped:
        index = ordered.index(station)
        neighbours = [widths[ordered[j]] for j in (index - 1, index + 1)
                      if 0 <= j < len(ordered)]
        lines.append(f"| RS {station:.0f} | {widths[station]:.0f} m | "
                     + " / ".join(f"{n:.0f} m" for n in neighbours) + " |")

    median_q = 8.1
    at_median = means[means.discharge_bc == median_q].set_index("variant")
    lines += [
        "",
        f"## Reach means at {median_q} m3/s",
        "",
        "| geometry | depth (m) | velocity (m/s) | top width (m) |",
        "|---|---|---|---|",
    ]
    for variant, row in at_median.iterrows():
        lines.append(f"| {variant} | {row.depth:.3f} | {row.velocity:.3f} | "
                     f"{row.top_width:.1f} |")

    if not shifts.empty and "max_abs_shift" in shifts:
        trimmed = shifts[shifts.variant == TRIMMED]
        worst = float(trimmed["max_abs_shift"].iloc[0]) if len(trimmed) else np.nan
        typical = float(trimmed["mean_abs_shift"].iloc[0]) if len(trimmed) else np.nan
        share = 100 * worst / RMSE if np.isfinite(worst) else np.nan

        verdict = (
            "Excluding them would change published conclusions, so it should be "
            "done - and every number in the project restated against the new "
            "geometry."
            if share >= 10 else
            "Excluding them would not change any conclusion. They stay in, "
            "flagged, and this file is the reason why."
        )
        lines += [
            "",
            "## What dropping them does to the predictions",
            "",
            "Every observation re-predicted with each geometry's hydraulics, "
            "chemistry and date held fixed.",
            "",
            "| geometry | mean predicted DO (mg/L) | mean shift | worst shift |",
            "|---|---|---|---|",
        ]
        for _, row in shifts.iterrows():
            lines.append(
                f"| {row.variant} | {row.mean_prediction:.3f} | "
                f"{row.get('mean_abs_shift', np.nan):.3f} | "
                f"{row.get('max_abs_shift', np.nan):.3f} |"
            )
        lines += [
            "",
            "## Verdict",
            "",
            f"Dropping the four sections moves predictions by {typical:.3f} mg/L "
            f"on average and {worst:.3f} mg/L at worst - {share:.0f}% of the "
            f"model's {RMSE:.3f} mg/L RMSE.",
            "",
            verdict,
            "",
            f"For comparison, the roughness constant is worth up to "
            f"{100 * MANNING_WORST / RMSE:.0f}% of the same error "
            f"(`MANNING_SENSITIVITY.md`). Two independent choices in the "
            f"geometry pipeline each account for a comparable share of the "
            f"model's error - which says the limit on this project is the "
            f"hydraulic model, not the regression on top of it.",
        ]

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.exit(main())
