"""Train and save the models the API serves.

Two models are produced, deliberately:

``dissolved_oxygen``
    Predicts observed dissolved oxygen from physical and seasonal drivers.
    **Labels are real measurements.** This is the honest model - R2 ~0.44 under
    grouped cross-validation, barely ahead of a persistence baseline.

``hsi``
    Predicts the synthetic Habitat Suitability Index. **Labels are generated by
    this repository**, so its R2 ~0.99 measures function recovery, not ecological
    skill. It is served because scenario analysis needs a bounded habitat score,
    and it is labelled as synthetic everywhere it appears.

Serving only the impressive one would be misleading; serving only the honest one
would drop the habitat framing the project is about. Both ship, each carrying its
own caveats, and the API returns them with every prediction.

    python scripts/train_models.py
"""

from __future__ import annotations

import glob
import json
import sys

import pandas as pd

from aquanexus.config import settings
from aquanexus.data.dataset import (
    DO_FEATURES,
    DO_RANGE,
    build_state_vectors,
    build_water_quality_dataset,
    feature_columns,
)
from aquanexus.data.loader import filter_stations, load_many
from aquanexus.logger import get_logger
from aquanexus.ml.explainer import collinear_pairs
from aquanexus.ml.models import HabitatPredictor, ModelConfig
from aquanexus.ml.splits import grouped_split
from aquanexus.ml.validator import ModelValidator

log = get_logger("scripts.train_models")

def training_ranges(dataset, features) -> dict:
    """Observed min/max per feature, so the API can flag out-of-range requests.

    Quantiles rather than raw extremes would hide the true edge of what the model
    has seen, which is exactly what a caller needs to know.
    """
    ranges = {}
    for name in features:
        column = dataset[name].dropna()
        if len(column) and column.dtype.kind in "fiu":
            ranges[name] = [float(column.min()), float(column.max())]
    return ranges


def save_background(dataset, features, target: str, limit: int = 100) -> str:
    """Persist a sample of the training rows for SHAP to explain against.

    Without this the API has no reference distribution and falls back to
    explaining a request against itself, which returns a contribution of exactly
    zero for every feature - an explanation that is not wrong so much as empty.
    Saved next to the model so the two travel together.
    """
    rows = dataset[features].dropna(how="all")
    if len(rows) > limit:
        rows = rows.sample(limit, random_state=settings.RANDOM_SEED)

    path = settings.MODELS_DIR / f"{target}_background.csv"
    rows.to_csv(path, index=False)
    log.info("background for %s: %d rows -> %s", target, len(rows), path.name)
    return path.name


def collinearity(dataset, features) -> list[list[str]]:
    """Feature pairs that move together in training, for the API to disclose.

    SHAP divides credit between collinear features arbitrarily, so a caller
    reading per-feature contributions needs to know which of them are the same
    signal wearing different names. Serving the explanation without this is
    serving a ranking that cannot be ranked.
    """
    pairs = collinear_pairs(dataset, features)
    return [[row.feature_a, row.feature_b] for row in pairs.itertuples()]


CAVEATS = {
    "dissolved_oxygen": [
        "Labels are real measurements from the 公共用水域 monitoring record.",
        "Trained on 138 samples from 4 stations on the Ayase; treat as indicative.",
        "Beats a persistence baseline by only 0.06 R2 and loses to it on MAE.",
        "Under-predicts oxygen by about 2 mg/L at low flow (< ~2 m3/s), which is "
        "where oxygen stress matters most. Low-flow predictions are unreliable.",
    ],
    "hsi": [
        "SYNTHETIC LABELS. HSI is generated from ecological response curves in "
        "this repository, not measured in the field.",
        "High accuracy here measures recovery of a known function, not "
        "ecological skill.",
        "Suitability is defined for a lowland warmwater cyprinid assemblage.",
    ],
}


def train_dissolved_oxygen(observations, sweep):
    dataset = build_water_quality_dataset(observations, sweep)
    features = [f for f in DO_FEATURES if f in dataset.columns]

    # Ridge, because it cross-validates better than either tree model at this
    # sample size - see docs/ML_METHODOLOGY.md.
    config = ModelConfig(model_type="linear", output_range=DO_RANGE)
    report = ModelValidator(dataset, features, "dissolved_oxygen", "station").run(
        model_types=("linear", "random_forest", "xgboost"), output_range=DO_RANGE
    )
    log.info("dissolved oxygen validation:\n%s", report.table().round(3).to_string(index=False))

    model = HabitatPredictor(config).fit(dataset[features], dataset["dissolved_oxygen"])
    path = model.save(settings.MODELS_DIR / "dissolved_oxygen_v1.joblib")

    best = report.best()
    return path, {
        "target": "dissolved_oxygen",
        "unit": "mg/L",
        "model_type": config.model_type,
        "features": features,
        "n_train": int(len(dataset)),
        "output_range": list(DO_RANGE),
        "labels": "observed",
        "metrics": {"rmse": best.rmse, "mae": best.mae, "r2": best.r2,
                    "validation": "grouped CV, each station held out"},
        "training_ranges": training_ranges(dataset, features),
        "collinear_pairs": collinearity(dataset, features),
        "background": save_background(dataset, features, "dissolved_oxygen"),
        "caveats": CAVEATS["dissolved_oxygen"],
    }


def train_hsi(observations, sweep):
    dataset = build_state_vectors(observations, sweep)
    features = feature_columns(dataset)

    config = ModelConfig(model_type="xgboost", output_range=(0.0, 1.0))
    split = grouped_split(dataset)
    (X_train, y_train), (X_val, y_val), (X_test, y_test) = split.apply(dataset, features)

    model = HabitatPredictor(config).fit(X_train, y_train, validation=(X_val, y_val))

    from aquanexus.ml.evaluator import evaluate

    metrics = evaluate(y_test, model.predict(X_test), "xgboost", "grouped",
                       baseline=float(y_train.mean()))
    log.info("hsi: RMSE %.4f R2 %.3f", metrics.rmse, metrics.r2)

    path = model.save(settings.MODELS_DIR / "hsi_v1.joblib")
    return path, {
        "target": "hsi",
        "unit": "index 0-1",
        "model_type": config.model_type,
        "features": features,
        "n_train": int(len(X_train)),
        "output_range": [0.0, 1.0],
        "labels": "SYNTHETIC",
        "metrics": {"rmse": metrics.rmse, "mae": metrics.mae, "r2": metrics.r2,
                    "validation": "grouped CV, observations held out"},
        "training_ranges": training_ranges(dataset, features),
        "collinear_pairs": collinearity(dataset, features),
        "background": save_background(dataset, features, "hsi"),
        "caveats": CAVEATS["hsi"],
    }


def main() -> int:
    settings.ensure_dirs()

    files = sorted(glob.glob(str(settings.RAW_DIR / "waterquality" / "saitama_*.xlsx")))
    if not files:
        log.error("no water quality files; run scripts/download_data.py first")
        return 1
    sweep_path = settings.PROCESSED_DIR / "ayase_flow_sweep.csv"
    if not sweep_path.is_file():
        log.error("no flow sweep at %s; run scripts/build_geometry.py first", sweep_path)
        return 1

    observations = filter_stations(load_many(files), water_body=settings.RIVER_NAME_JA)
    sweep = pd.read_csv(sweep_path)
    log.info("%d observations, sweep of %d discharge(s)",
             len(observations), sweep["discharge_bc"].nunique())

    manifest = {"river": settings.RIVER_NAME, "river_ja": settings.RIVER_NAME_JA,
                "crs_epsg": settings.CRS_EPSG, "models": {}}

    for name, trainer in (("dissolved_oxygen", train_dissolved_oxygen), ("hsi", train_hsi)):
        try:
            path, meta = trainer(observations, sweep)
            meta["path"] = path.name
            manifest["models"][name] = meta
            log.info("saved %s", path)
        except Exception as exc:  # noqa: BLE001 - one model must not stop the other
            log.error("%s failed: %s", name, exc)

    if not manifest["models"]:
        return 1

    manifest_path = settings.MODELS_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False),
                             encoding="utf-8")
    log.info("wrote %s", manifest_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
